NORMAL_DIR = "dataset/normal"
ABNORMAL_DIR = "dataset/abnormal"
RESULT_DIR = "result"

MAX_SEQ_LEN = 10

INPUT_DIM = 3
HIDDEN_DIM = 16
NUM_LAYERS = 2
NUM_CLASSES = 2
LEARNING_RATE = 1e-4
NUM_EPOCHS = 200
BATCH_SIZE = 8

# K-fold 分割
KFOLD_SPLITS = 5
SEED = 42